---
name: LT1-Mini
description: |
  Base for the LT1-Mini flashlight
license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2022
resources:
  # foo: https://example.com
fusion_link: https://a360.co/3ymzbhn
links:
  # Thingiverse: https://www.thingiverse.com/thing:xxxx
  # Printables: https://foo.com
  # GrabCad: https://foo.com
  # Hackster.io: https://hackster.io/foo
  # Hackaday: https://hackaday.io/foo
  # Reddit: https://www.reddit.com/r/foo
  # Github: https://github.com/foo
  # Blog: https://foo.com
